# Generated by Django 5.2.8 on 2025-12-14 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=50, unique=True, verbose_name='Зав. № машины')),
                ('engine_number', models.CharField(max_length=50, verbose_name='Зав. № двигателя')),
                ('transmission_number', models.CharField(max_length=50, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_number', models.CharField(max_length=50, verbose_name='Зав. № ведущего моста')),
                ('steerable_axle_number', models.CharField(max_length=50, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(max_length=200, verbose_name='Договор поставки №, дата')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=200, verbose_name='Грузополучатель')),
                ('delivery_address', models.TextField(verbose_name='Адрес поставки')),
                ('equipment', models.TextField(blank=True, verbose_name='Комплектация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(limit_choices_to={'groups__name': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='client_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('service_company', models.ForeignKey(limit_choices_to={'groups__name': 'service_company'}, on_delete=django.db.models.deletion.PROTECT, related_name='service_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'ordering': ['-shipment_date'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tech_model', 'Модель техники'), ('engine_model', 'Модель двигателя'), ('transmission_model', 'Модель трансмиссии'), ('drive_axle_model', 'Модель ведущего моста'), ('steerable_axle_model', 'Модель управляемого моста'), ('maintenance_type', 'Вид ТО'), ('failure_node', 'Узел отказа'), ('recovery_method', 'Способ восстановления'), ('service_company_ref', 'Сервисная компания (справочник)')], max_length=50, verbose_name='Тип справочника')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('work_order_number', models.CharField(max_length=50, verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine', verbose_name='Машина')),
                ('service_company', models.ForeignKey(limit_choices_to={'groups__name': 'service_company'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('type', models.ForeignKey(limit_choices_to={'type': 'maintenance_type'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_type_records', to='myapp.reference', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Техническое обслуживание',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(limit_choices_to={'type': 'drive_axle_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='drive_axle_model_machines', to='myapp.reference', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(limit_choices_to={'type': 'engine_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='engine_model_machines', to='myapp.reference', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='steerable_axle_model',
            field=models.ForeignKey(limit_choices_to={'type': 'steerable_axle_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='steerable_axle_model_machines', to='myapp.reference', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='tech_model',
            field=models.ForeignKey(limit_choices_to={'type': 'tech_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='tech_model_machines', to='myapp.reference', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(limit_choices_to={'type': 'transmission_model'}, on_delete=django.db.models.deletion.PROTECT, related_name='transmission_model_machines', to='myapp.reference', verbose_name='Модель трансмиссии'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_time', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(blank=True, verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.PositiveIntegerField(editable=False, verbose_name='Время простоя техники')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('service_company', models.ForeignKey(limit_choices_to={'groups__name': 'service_company'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine', verbose_name='Машина')),
                ('failure_node', models.ForeignKey(limit_choices_to={'type': 'failure_node'}, on_delete=django.db.models.deletion.PROTECT, related_name='failure_node_complaints', to='myapp.reference', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(limit_choices_to={'type': 'recovery_method'}, on_delete=django.db.models.deletion.PROTECT, related_name='recovery_method_complaints', to='myapp.reference', verbose_name='Способ восстановления')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'ordering': ['-failure_date'],
            },
        ),
    ]
